spring:
  application:
    name: finance-zuul-proxy

server:
  port: 8300

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    mf-service:
      path: /mf-service/**
      url: http://localhost:8302
    db-service:
      path: /db-service/**
      url: http://localhost:8303
    mf-feeder-service:
      path: /mf-feeder-service/**
      url: http://localhost:8304