spring:
  application:
    name: db-service

server:
  port: 8303

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck :
      enabled : true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka
    lease:
      duration: 5