spring:
  application:
    name: mf-feeder-service

server:
  port: 8304

eureka:
  client:
    healthcheck :
      enabled : true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka
